/**
 * 인제스트 기본값 (03 §1.3 · D12 · D60). 이 상수들이 `IngestSpec` 으로 Rust 에 건너간다 —
 * 무엇을 읽지 않을지는 도메인 판단이므로 TS 가 소유한다.
 */

/** 경로 앞머리 제외 — 남의 코드이거나 빌드 산출물이다. */
export const EXCLUDE_DIRS = [
  'node_modules', 'dist', 'build', 'out', '.next', 'target', 'vendor', 'Pods',
  '.dart_tool', 'DerivedData', '__pycache__', '.venv', 'venv', 'coverage',
  '.turbo', '.expo', 'android/app/build',
] as const;

/** 파일명 제외 — 잠금 파일과 생성물. `.d.ts` 는 D60 에 따라 여기서 빠진다. */
export const EXCLUDE_FILES = [
  'package-lock.json', 'pnpm-lock.yaml', 'yarn.lock', 'bun.lockb', 'Cargo.lock',
  'pubspec.lock', 'Package.resolved', 'poetry.lock', 'uv.lock', 'go.sum',
  '*.min.js', '*.map', '*.d.ts', '*.g.dart', '*.freezed.dart', '*.pb.go',
  '*_pb2.py', '*.generated.*',
] as const;

/** `ignore` 크레이트의 override 문법. 디렉터리는 하위 전체를 덮는다. */
export const EXCLUDE_GLOBS: readonly string[] = [
  ...EXCLUDE_DIRS.map((d) => `${d}/**`),
  ...EXCLUDE_FILES,
];

/** 첫 5줄에 이 중 하나가 있으면 사람이 쓴 코드가 아니다 (03 §1.3). */
export const GENERATED_MARKERS = [
  '@generated', 'DO NOT EDIT', '<auto-generated', 'Code generated by',
] as const;

/** 01 §3.1 · D12 의 기본값. `settings` 로 덮어쓸 수 있다. */
export const LIMITS = {
  maxCommits: 2_000,
  maxFilesPerCommit: 200,
  maxFiles: 50_000,
  maxLineBytes: 20_000,
  maxFileBytes: 512 * 1024,
} as const;

/** 사용처가 12줄을 넘으면 카드로 내기엔 크다 (03 §2.5). */
export const OVERSIZE_SITE_LINES = 12;
/** 5,000줄 넘는 파일은 개념당 사용처 20개까지만 (03 §2.5). */
export const OVERSIZE_FILE_LINES = 5_000;
export const OVERSIZE_SITES_PER_CONCEPT = 20;

/**
 * 테스트 파일 — 사용처로는 유효하지만 구멍 지도의 `essential` 집계에서는 뺀다 (D60).
 * 테스트에만 있는 개념을 「내 앱의 핵심 문법」으로 세면 지도가 거짓말을 한다.
 */
const TEST_PATH = /(^|\/)(__tests__|test|tests|spec)\/|\.(test|spec)\.[a-z]+$/;

export const isTestPath = (path: string): boolean => TEST_PATH.test(path);
